//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEntityCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cell
    {
        public int CellID { get; set; }
        public Nullable<int> AisleID { get; set; }
        public Nullable<int> XCoordinate { get; set; }
        public Nullable<int> YCoordinate { get; set; }
        public Nullable<int> ZCoordinate { get; set; }
        public int Id { get; set; }
        public int company_id { get; set; }
    
        public virtual Aisle Aisle { get; set; }
        public virtual member member { get; set; }
        public virtual Company Company { get; set; }
    }
}
