//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEntityCRUD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
 
    using System.Data.Entity.SqlServer;


    public partial class wpfCrudEntities1 : DbContext
    {
        public wpfCrudEntities1()
            : base("name=wpfCrudEntities1")
        {
            // Retry strategy for SQL Azure
            this.Database.CommandTimeout = 180; // Adjust timeout as needed
            var strategy = new SqlAzureExecutionStrategy();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aisle> Aisles { get; set; }
        public virtual DbSet<Cell> Cells { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<PackingList> PackingLists { get; set; }
        public virtual DbSet<TaskHistory> TaskHistories { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
