//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEntityCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public member()
        {
            this.Cells = new HashSet<Cell>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Quantity { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string Despatched { get; set; }
        public string Supplier { get; set; }
        public string PackingList { get; set; }
        public string Quantity_r { get; set; }
        public string Sold { get; set; }
        public string Invoice { get; set; }
        public string Barcode { get; set; }
        public int company_id { get; set; }
        public Nullable<int> warehousesId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cell> Cells { get; set; }
        public virtual Company Company { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
