//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEntityCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingList
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Quantity { get; set; }
        public int company_id { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
