//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEntityCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public string Action { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string Details { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
